services:
  - type: web
    name: devtracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn devtracker.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: devtracker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: devtracker-db
    databaseName: devtracker
    user: devtracker
